version: '3'

services: 
   db:
      container_name: db-1
      image: postgres
      environment:
         - POSTGRES_DB=postgres
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=postgres
      ports:
         - "50001:5432"

   web:
      container_name: django-1
      build: .
      command: python manage.py runserver 0.0.0.0:8000 
      #command: ["./scripts/command-dev.sh"]
      volumes: 
         - .:/code
      ports:
         - "8000:8000"
      depends_on:
            - db
