# Generated by Django 3.2.12 on 2023-10-13 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_contenido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='título',
            new_name='titulo',
        ),
    ]
