# Generated by Django 4.2.6 on 2023-10-18 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_título_post_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imagen',
            new_name='imagenes',
        ),
    ]
